# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b717953d73c30cc6c96ed537ef3560287524b31a6fc57d677ad0c2d306b16b26bffd067fd6d2f573970f9542524d99eb383baf44b294f839d00667fe5458b920

test:
  secret_key_base: 7875d81e38e620e4d7ccba1a1f6dd3234ff63fdc8f62e83b78fec5059f4d35b6ee059ec415bd09b439a229b1869c35d29bbbd769c786c29a21c3a9a4aef9a6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
